-- V11: 출석·공지 스키마 + 활동 피드 인덱스 (D-127·D-128·D-131·D-135).
-- 이미 커밋된 V1~V10은 수정하지 않는다(conventions §9) — 이 파일이 phase 6의 신규 테이블 2개와
-- 기존 notification 테이블용 인덱스 1개를 담는다.

-- (1) attendance — 출석 기록(glossary "출석", policies §6). 출석은 차감과 무관한 참고 데이터이며,
-- 저녁반 0.5회 차감(§4.2)만 예외적으로 attendance 행 하나에 연결된다(pass_transaction_id).
--
-- 유니크는 **조건(WHERE) 없는 일반 UNIQUE (class_session_id, member_id)**다. 예약의 부분 유니크
-- `ux_reservation_session_member_active ... WHERE status = 'ACTIVE'`(V6)를 그대로 복사하지 않는다 —
-- 예약은 취소 후 재예약을 허용해야 해서 부분 유니크가 맞지만, 출석은 레코드가 있으면 이미 체크된
-- 것이고 ABSENT↔ATTENDED 정정은 새 행이 아니라 같은 행의 status UPDATE로 처리한다(D-127). 이중
-- 출석 = 이중 차감으로 이어질 수 있어(T-06-03) 이 유니크가 그 방어선이다.
CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_session_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,                  -- ATTENDED / ABSENT (D-127 — 저녁반은 ATTENDED만 씀)
    pass_transaction_id BIGINT,                    -- 저녁반 0.5회 차감 연결(D-128). 예약제/1:1은 항상 NULL
    checked_by_admin_id BIGINT NOT NULL,
    checked_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_attendance_class_session FOREIGN KEY (class_session_id) REFERENCES class_session (id),
    CONSTRAINT fk_attendance_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_attendance_pass_transaction FOREIGN KEY (pass_transaction_id) REFERENCES pass_transaction (id),
    CONSTRAINT fk_attendance_checked_by FOREIGN KEY (checked_by_admin_id) REFERENCES admin (id),
    CONSTRAINT uq_attendance_member_session UNIQUE (class_session_id, member_id)
);

CREATE INDEX idx_attendance_member ON attendance (member_id, checked_at);  -- CR-03 마지막 출석일 벌크 조회 대비

-- (2) notice — 공지사항(glossary "공지사항", D-131). 제목·본문만 존재한다(첨부·고정 없음).
-- hard delete 확정(D-131)이라 soft delete 컬럼(deleted_at 등)을 두지 않는다.
CREATE TABLE notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_by_admin_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notice_created_by FOREIGN KEY (created_by_admin_id) REFERENCES admin (id)
);

CREATE INDEX idx_notice_created_at ON notice (created_at DESC);  -- 최신순 페이지 조회(NOTICE-01/02)

-- attendance·notice 어디에도 branch_id를 두지 않는다 — 출석은 class_session을 통해 지점이 간접
-- 결정되고, 공지는 지점 구분 요구가 없다(requirements NOTICE-01/02가 지점 스코프를 요구하지 않음).

-- (3) 활동 피드 인덱스(D-135) — notification은 건드리지 않는다(수신자 컬럼 추가 금지, D-097).
-- 기존 idx_notification_unread(is_read, occurred_at DESC)는 활동 피드가 is_read 조건 없이
-- occurred_at 역순 전체 조회를 하는 패턴에는 활용되지 않을 수 있어 별도 인덱스를 추가한다.
CREATE INDEX idx_notification_occurred_at ON notification (occurred_at DESC);
