-- V2: Branch/Member/Admin/AdminBranch 초기 스키마.
-- D-04 최소 스키마 원칙: 확실한 정체성 컬럼만 만든다. 카카오 식별자·관리자 로그인 자격(ID/PW)·역할 컬럼은
-- 넣지 않는다 — 인증 관련 컬럼은 Phase 2에서 V3 이후 마이그레이션으로 추가된다.

CREATE TABLE branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_branch_name UNIQUE (name)
);

-- 송파점 시드 (D-09). 지점 관리 API가 스코프 밖이라 마이그레이션이 유일한 데이터 주입 경로다.
-- id를 명시하지 않는다 — identity 시퀀스가 어긋나면 이후 테스트/운영 데이터 삽입 순서가 꼬인다.
INSERT INTO branch (name) VALUES ('송파점');

CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    -- 온보딩(Phase 2) 전에는 값이 없다 (D-05, policies §5.1) — nullable
    name VARCHAR(50),
    phone_number VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_member_branch FOREIGN KEY (branch_id) REFERENCES branch (id)
);

CREATE INDEX idx_member_branch ON member (branch_id);

CREATE TABLE admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    -- 로그인 자격(ID/PW)은 D-04에 따라 이번 마이그레이션에 포함하지 않는다. Phase 2가 V3 이후로 추가한다.
);

-- admin_branch: Admin↔Branch 다대다 매핑. 서로게이트 PK(id) + UNIQUE(admin_id, branch_id) 조합을 쓴 이유:
-- add-migration §2 "PK는 항상 id" 관례와의 일관성을 위해 복합 PK 대신 이 방식을 선택했다.
CREATE TABLE admin_branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_admin_branch_admin FOREIGN KEY (admin_id) REFERENCES admin (id),
    CONSTRAINT fk_admin_branch_branch FOREIGN KEY (branch_id) REFERENCES branch (id),
    CONSTRAINT uq_admin_branch UNIQUE (admin_id, branch_id)
);

CREATE INDEX idx_admin_branch_branch ON admin_branch (branch_id);
