-- V3: 인증 스키마 확정. D-030(최소 스키마 원칙)이 Phase 2로 미뤄 둔 카카오 식별자·관리자 로그인
-- 자격·refresh 토큰을 여기서 채운다. member/admin은 Phase 1까지 INSERT 경로가 없어 비어 있음을
-- 전제로 NOT NULL 컬럼을 바로 추가한다 — 수동으로 넣은 로컬 데이터가 있으면
-- `docker compose down -v`로 초기화가 필요하다.

-- member 확장: 카카오 식별자 + 거절 사유 (D-034)
ALTER TABLE member
    ADD COLUMN kakao_id BIGINT NOT NULL,
    ADD COLUMN rejection_reason VARCHAR(500);

ALTER TABLE member
    ADD CONSTRAINT uq_member_kakao_id UNIQUE (kakao_id);

-- phone_number에는 UNIQUE를 걸지 않는다 — 가족 공유폰 등 정당한 중복이 있고, policies §5.1도
-- 요구하지 않는다 (D-041). 중복 가입 방지는 kakao_id UNIQUE가 담당한다.

-- 상태 필터 조회 성능 (D-035의 회원 목록 상태 필터가 항상 걸린다)
CREATE INDEX idx_member_status ON member (status);

-- admin 확장: ID/PW 로그인 자격 (D-045)
ALTER TABLE admin
    ADD COLUMN login_id VARCHAR(50) NOT NULL,
    ADD COLUMN password_hash VARCHAR(100) NOT NULL;

ALTER TABLE admin
    ADD CONSTRAINT uq_admin_login_id UNIQUE (login_id);

-- role 컬럼을 두지 않는다 — 역할은 "어느 테이블(member/admin) 행인가"로 이미 결정되고,
-- PrincipalType이 코드에서 그 구분을 담당한다 (D-040 인가 설계).

-- refresh_token: access 토큰 재발급용 자격증명. 원문 토큰은 저장하지 않고 SHA-256 hex만 저장한다
-- (D-036) — DB 덤프가 유출돼도 그 값으로 토큰을 재구성할 수 없다.
CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT,
    admin_id BIGINT,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_refresh_token_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_refresh_token_admin FOREIGN KEY (admin_id) REFERENCES admin (id),
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash),
    -- 주체는 정확히 하나만 채워진다 — Member/Admin이 별도 테이블이라 단일 FK로 표현할 수 없고,
    -- principal_type 문자열 조합은 참조 무결성을 잃는다 (D-037).
    CONSTRAINT ck_refresh_token_principal CHECK ((member_id IS NULL) <> (admin_id IS NULL))
);

-- 상태 변경 시 해당 주체의 미폐기 토큰을 전부 찾는 경로(D-044)가 이 인덱스를 탄다.
CREATE INDEX idx_refresh_token_member ON refresh_token (member_id);
CREATE INDEX idx_refresh_token_admin ON refresh_token (admin_id);
