-- V4: 이용권 스키마 (Phase 3). D-055~D-067 결정에 근거한다.
-- - D-060: Pass는 JPA @Inheritance 없이 단일 엔티티 + type 판별 컬럼.
-- - D-061: pass_transaction은 reason(코드)·note(자유 텍스트) 분리.
-- - D-063: EveningMembershipTerm(개월 수)은 저장하지 않는다 — end_date만 남는다.
-- - D-064: 저장 상태는 ACTIVE/CANCELED 2종뿐 — 만료·소진은 조회 시점 계산.
-- - D-065: 등록 취소 시 잔여가 이미 0이면 상쇄 이력을 남기지 않는다 (amount <> 0 CHECK와 정합).
-- - D-066: 유효기간 경계는 종료일 포함.
-- - D-067: pass는 branch_id를 보유한다(발급 지점 귀속).
-- Pitfall 5(RESEARCH): pass_transaction/pass_period_change는 "주체 중 정확히 하나" CHECK를 두지
-- 않는다 — 이번 phase의 사유 코드는 전부 관리자 주체이고, Phase 5의 배치 차감은 주체가 없다.

CREATE TABLE pass (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    remaining_count DECIMAL(4, 1),
    registered_by_admin_id BIGINT NOT NULL,
    canceled_at TIMESTAMPTZ,
    cancel_reason VARCHAR(500),
    canceled_by_admin_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_pass_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_pass_branch FOREIGN KEY (branch_id) REFERENCES branch (id),
    CONSTRAINT fk_pass_registered_by_admin FOREIGN KEY (registered_by_admin_id) REFERENCES admin (id),
    CONSTRAINT fk_pass_canceled_by_admin FOREIGN KEY (canceled_by_admin_id) REFERENCES admin (id),
    -- 타입별 컬럼 규칙을 DB가 강제한다(D-060) — 기간제는 remaining_count가 없고, 횟수제는 반드시 있다.
    CONSTRAINT ck_pass_remaining_count_by_type CHECK (
        (type = 'EVENING_MEMBERSHIP' AND remaining_count IS NULL) OR
        (type IN ('SESSION_PASS', 'LESSON_PASS') AND remaining_count IS NOT NULL)
    ),
    CONSTRAINT ck_pass_period CHECK (end_date >= start_date),
    -- 취소 메타데이터 완전성(D-059) — CANCELED면 셋 다 채워지고, 아니면 셋 다 비어 있어야 한다.
    CONSTRAINT ck_pass_cancellation CHECK (
        (status = 'CANCELED' AND canceled_at IS NOT NULL AND cancel_reason IS NOT NULL AND canceled_by_admin_id IS NOT NULL) OR
        (status <> 'CANCELED' AND canceled_at IS NULL AND cancel_reason IS NULL AND canceled_by_admin_id IS NULL)
    )
);

CREATE INDEX idx_pass_member ON pass (member_id);

-- pass_transaction: ±수량 원장(D-057 "PassTransaction은 ±수량 원장 역할에 고정"). append-only.
CREATE TABLE pass_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pass_id BIGINT NOT NULL,
    amount DECIMAL(4, 1) NOT NULL,
    reason VARCHAR(30) NOT NULL,
    note VARCHAR(500),
    admin_id BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_pass_transaction_pass FOREIGN KEY (pass_id) REFERENCES pass (id),
    CONSTRAINT fk_pass_transaction_admin FOREIGN KEY (admin_id) REFERENCES admin (id),
    -- 의미 없는 0 수량 이력을 DB가 거부한다(D-065와 정합).
    CONSTRAINT ck_pass_transaction_amount_nonzero CHECK (amount <> 0)
);

-- 이력 필터(D-058)가 이 인덱스를 탄다.
CREATE INDEX idx_pass_transaction_pass ON pass_transaction (pass_id);

-- pass_period_change: 기간·유효기간 변경 이력(D-057). append-only.
CREATE TABLE pass_period_change (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pass_id BIGINT NOT NULL,
    previous_start_date DATE NOT NULL,
    previous_end_date DATE NOT NULL,
    new_start_date DATE NOT NULL,
    new_end_date DATE NOT NULL,
    reason VARCHAR(500) NOT NULL,
    admin_id BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_pass_period_change_pass FOREIGN KEY (pass_id) REFERENCES pass (id),
    CONSTRAINT fk_pass_period_change_admin FOREIGN KEY (admin_id) REFERENCES admin (id),
    CONSTRAINT ck_pass_period_change_period CHECK (new_end_date >= new_start_date)
);

CREATE INDEX idx_pass_period_change_pass ON pass_period_change (pass_id);
