-- V6: 시간표·예약·알림 스키마. D-090~D-097, D-021에 근거한다.
-- - D-093: ClassSchedule은 Flyway 시드로 고정(관리자 CRUD API 없음). 정원은 요일+시각 단위로 여기에 둔다.
-- - D-094: ClassSession은 "필요할 때 생성"한다. 시작·종료 시각·정원을 ClassSchedule에서 복사해
--   자기 컬럼으로 보유한다 — 나중에 "그날만 시간 옮기기"를 마이그레이션 없이 붙이기 위함이고,
--   시간표를 참조만 하면 시간표 수정이 과거 수업까지 소급 변경해 지난 기록이 틀어진다.
-- - D-090: 예약 취소는 물리 삭제가 아니라 상태 전환. 취소한 타임의 재예약은 허용하므로
--   (member, class_session) 전체 유니크 제약은 쓸 수 없고, 활성 예약만 대상인 부분 유니크 인덱스로 막는다.
-- - D-021: "초과 예약 0건"은 애플리케이션 조건문으로 보장할 수 없다 — DB 제약이 최종 방어선이다.
--   정원은 class_session.reserved_count에 대한 조건부 UPDATE, 1:1은 부분 유니크 인덱스가 1차 방어선.
-- - reservation에 class_type/class_date/start_time을 비정규화한 이유: Postgres 부분 유니크 인덱스의
--   WHERE 절과 인덱스 대상 컬럼은 반드시 같은 테이블 안에서 나와야 한다. class_session을 조인해서는
--   부분 인덱스를 만들 수 없어, class_session이 ClassSchedule의 값을 복사한 것과 같은 이유로 복사한다.
-- - D-097: notification의 수신자는 관리자뿐이라(회원용 알림 없음) 수신자 컬럼이 없다. 휴강 알림은
--   세션당 1건 요약형이라(그렇지 않으면 정원 10명 휴강 시 알림 10건이 쏟아져 알림함이 폭증하고
--   Phase 6의 미확인 카운트가 왜곡된다) reservation_id 단일 FK 외에 class_session_id(nullable)를 둔다.

CREATE TABLE class_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,          -- java.time.DayOfWeek name(), EnumType.STRING
    class_type VARCHAR(20) NOT NULL,           -- EVENING / SESSION / LESSON
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    capacity INT,                              -- SESSION/LESSON만 NOT NULL, EVENING은 NULL
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_class_schedule_branch FOREIGN KEY (branch_id) REFERENCES branch (id),
    CONSTRAINT uq_class_schedule UNIQUE (branch_id, day_of_week, class_type, start_time),
    CONSTRAINT ck_class_schedule_period CHECK (end_time > start_time),
    -- V4 ck_pass_remaining_count_by_type과 동일한 사고: 타입별 필수 컬럼을 DB가 강제한다.
    CONSTRAINT ck_class_schedule_capacity_by_type CHECK (
        (class_type = 'EVENING' AND capacity IS NULL) OR
        (class_type IN ('SESSION', 'LESSON') AND capacity IS NOT NULL AND capacity > 0)
    )
);

CREATE TABLE class_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_schedule_id BIGINT NOT NULL,
    class_date DATE NOT NULL,
    class_type VARCHAR(20) NOT NULL,           -- 조회 편의를 위한 복사(항상 schedule과 동일)
    start_time TIME NOT NULL,                  -- D-094: 시간표에서 복사, 자기 컬럼으로 보유
    end_time TIME NOT NULL,
    capacity INT,                              -- 복사 — 정원 조건부 UPDATE가 조인 없이 단일 테이블에서 끝나게 함
    reserved_count INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',  -- SCHEDULED / CANCELED(휴강)
    canceled_at TIMESTAMPTZ,
    cancel_reason VARCHAR(500),
    canceled_by_admin_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_class_session_schedule FOREIGN KEY (class_schedule_id) REFERENCES class_schedule (id),
    CONSTRAINT fk_class_session_canceled_by FOREIGN KEY (canceled_by_admin_id) REFERENCES admin (id),
    -- get-or-create 경쟁의 최종 방어선(D-094) — 동시에 두 요청이 같은 세션을 만들려 하면 하나만 성공한다.
    CONSTRAINT uq_class_session UNIQUE (class_schedule_id, class_date),
    CONSTRAINT ck_class_session_reserved_count CHECK (
        reserved_count >= 0 AND (capacity IS NULL OR reserved_count <= capacity)
    ),
    -- V4 ck_pass_cancellation과 동일한 완전성 검사 관례: 휴강이면 취소 메타데이터 3개가 전부 채워지고,
    -- 아니면 전부 비어 있어야 한다.
    CONSTRAINT ck_class_session_cancellation CHECK (
        (status = 'CANCELED' AND canceled_at IS NOT NULL AND cancel_reason IS NOT NULL AND canceled_by_admin_id IS NOT NULL) OR
        (status <> 'CANCELED' AND canceled_at IS NULL AND cancel_reason IS NULL AND canceled_by_admin_id IS NULL)
    )
);

CREATE INDEX idx_class_session_date ON class_session (class_date);  -- 주간 보드·2주 조회

CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    class_session_id BIGINT NOT NULL,
    pass_id BIGINT NOT NULL,                   -- 복구 대상 추적(D-091) — 원래 차감한 그 이용권으로 되돌린다
    -- 아래 3개 컬럼은 class_session에서 비정규화한 것 — 부분 유니크 인덱스 3종이 단일 테이블 안에서
    -- 성립해야 하기 때문이다(위 헤더 주석 참조).
    class_type VARCHAR(20) NOT NULL,
    class_date DATE NOT NULL,
    start_time TIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    reserved_at TIMESTAMPTZ NOT NULL,
    canceled_at TIMESTAMPTZ,
    canceled_by_member_id BIGINT,
    canceled_by_admin_id BIGINT,
    refunded BOOLEAN,                            -- CANCELED일 때만 값 존재(대리 취소 "복구 안 함" 대응)
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_reservation_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_reservation_session FOREIGN KEY (class_session_id) REFERENCES class_session (id),
    CONSTRAINT fk_reservation_pass FOREIGN KEY (pass_id) REFERENCES pass (id),
    CONSTRAINT fk_reservation_canceled_by_member FOREIGN KEY (canceled_by_member_id) REFERENCES member (id),
    CONSTRAINT fk_reservation_canceled_by_admin FOREIGN KEY (canceled_by_admin_id) REFERENCES admin (id),
    -- 취소면 canceled_at·refunded·취소 주체(회원/관리자 중 정확히 하나)가 채워지고, 아니면 넷 다 비어 있다.
    CONSTRAINT ck_reservation_cancellation CHECK (
        (status = 'CANCELED' AND canceled_at IS NOT NULL AND refunded IS NOT NULL
            AND ((canceled_by_member_id IS NOT NULL AND canceled_by_admin_id IS NULL)
              OR (canceled_by_member_id IS NULL AND canceled_by_admin_id IS NOT NULL))) OR
        (status <> 'CANCELED' AND canceled_at IS NULL AND refunded IS NULL
            AND canceled_by_member_id IS NULL AND canceled_by_admin_id IS NULL)
    )
);

-- ① 같은 세션에 같은 회원이 중복 예약하지 못한다(재예약은 취소 후에만) — D-090
CREATE UNIQUE INDEX ux_reservation_session_member_active
    ON reservation (class_session_id, member_id) WHERE status = 'ACTIVE';
-- ② 1:1(LESSON) 슬롯은 세션당 활성 예약이 최대 1건 — 정원 조건부 UPDATE와 별개의 1차 방어선
CREATE UNIQUE INDEX ux_reservation_lesson_slot_active
    ON reservation (class_session_id) WHERE status = 'ACTIVE' AND class_type = 'LESSON';
-- ③ 같은 회원이 같은 날짜·같은 시각에 두 건(SESSION+LESSON 등) 예약 못함 — D-092
CREATE UNIQUE INDEX ux_reservation_member_timeslot_active
    ON reservation (member_id, class_date, start_time) WHERE status = 'ACTIVE';

CREATE INDEX idx_reservation_member_active ON reservation (member_id, status);  -- 본인 목록(RESV-05)
CREATE INDEX idx_reservation_session ON reservation (class_session_id);         -- 스케줄보드 셀 명단
CREATE INDEX idx_reservation_pass_active ON reservation (pass_id, status);      -- D-089 등록 취소 선행 검사

-- notification: 관리자 인앱 알림(D-097). 수신자는 관리자뿐이라 수신자 컬럼이 없다 — 회원용 알림은
-- 요구사항에 조회 경로가 없어(NOTIF-01~03 어디에도 없음) 만들지 않는다.
CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(40) NOT NULL,
    reservation_id BIGINT,
    class_session_id BIGINT,                   -- 휴강 요약 알림 전용(세션당 1건, D-097)
    -- 비정규화 표시 정보 — Phase 6이 조회 시점 조인 없이 표시할 수 있도록 이벤트 발생 시점 값을 담는다.
    -- 회원명이 나중에 바뀌어도 "그때 그 알림"이 그대로 남는 것이 알림·활동 피드의 의미에 맞는다.
    member_name VARCHAR(50),
    class_type VARCHAR(20),
    class_date DATE,
    start_time TIME,
    message VARCHAR(500) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,    -- Phase 6(NOTIF-02)이 그대로 쓸 컬럼 — 선반영
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notification_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (id),
    CONSTRAINT fk_notification_class_session FOREIGN KEY (class_session_id) REFERENCES class_session (id),
    -- 어느 쪽도 없는 고아 알림을 막는다. 휴강 요약 알림은 class_session_id만, 예약 이벤트는 reservation_id를 갖는다.
    CONSTRAINT ck_notification_target CHECK (reservation_id IS NOT NULL OR class_session_id IS NOT NULL)
);

CREATE INDEX idx_notification_unread ON notification (is_read, occurred_at DESC);  -- Phase 6 폴링 대비
