-- V9: pass_transaction 시스템 주체 허용 + member 휴회 복귀 시각 + 배치 실행 이력 (D-105·D-106·D-108, D-110~D-113).
-- 이미 커밋된 V4·V8은 수정하지 않는다(conventions §9) — 이 파일로 세 가지를 새로 추가한다.

-- (1) pass_transaction 주체 CHECK 완화 — "정확히 하나" → "최대 하나" (D-110).
-- 배치(INACTIVITY)는 admin도 member도 아닌 시스템 주체라 둘 다 NULL이다. 기존 행은 전부 한쪽만
-- 채워져 있어 백필이 필요 없다 — 완화는 배치 행(둘 다 NULL)만 새로 허용하고, "둘 다 채움"은
-- 여전히 거부한다(T-05-03, 사람 조작 이력의 주체 누락 방지).
ALTER TABLE pass_transaction DROP CONSTRAINT ck_pass_transaction_subject;
ALTER TABLE pass_transaction ADD CONSTRAINT ck_pass_transaction_subject CHECK (
    NOT (admin_id IS NOT NULL AND member_id IS NOT NULL)
);

-- (2) 휴회 복귀 시각 — ON_LEAVE → ACTIVE 전이에서만 기록한다(D-105 기준일 후보 ③ 전용, D-111).
-- 다른 상태 전이(승인 PENDING→ACTIVE, 재활성화 INACTIVE→ACTIVE, 휴회 시작)는 이 컬럼을 건드리지
-- 않는다. 과거 복귀 이력은 데이터가 없어 후보에서 자연 제외되며 이는 의도된 동작이다.
ALTER TABLE member ADD COLUMN returned_from_leave_at TIMESTAMPTZ;

-- (3) 배치 실행 이력 (D-108·D-113) — 관측·복구 판단용이며 멱등성 판단에 쓰지 않는다.
-- "오늘 이미 실행했나"를 이 테이블로 판단하면 D-106의 상태 기반 설계가 무너진다.
CREATE TABLE batch_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_type VARCHAR(20) NOT NULL,                    -- SCHEDULED / MANUAL
    triggered_by_admin_id BIGINT,                         -- MANUAL일 때만 non-null
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ NOT NULL,
    processed_member_count INT NOT NULL,
    deducted_count INT NOT NULL,
    skipped_count INT NOT NULL,                           -- 경쟁 패배·대상 소진 스킵(정상 경로, D-113)
    status VARCHAR(20) NOT NULL,                           -- SUCCESS / PARTIAL_FAILURE
    error_summary VARCHAR(1000),
    CONSTRAINT fk_batch_execution_admin FOREIGN KEY (triggered_by_admin_id) REFERENCES admin (id),
    CONSTRAINT ck_batch_execution_trigger CHECK (
        (trigger_type = 'MANUAL' AND triggered_by_admin_id IS NOT NULL) OR
        (trigger_type = 'SCHEDULED' AND triggered_by_admin_id IS NULL)
    )
);

CREATE INDEX idx_batch_execution_started_at ON batch_execution (started_at);
